# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env: 
     TEST_1 : test

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: env
      - name: Test
        run: docker
      - name: Run PS
        shell: powershell
        run: |
          $filepath = "$($RUNNER_WORKSPACE)\test"
          echo $filePath
          echo ${env:TEST_1}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo echo ${env:RUNNER_WORKSPACE}
          dir $RUNNER_WORKSPACE
          
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print runner environmrnt var
        run: env
